version: "3"

services:
  node:
    image: "node:18"
    user: "node"
    working_dir: /app
    environment:
      NODE_ENV: "development"
      ESLINT_NO_DEV_ERRORS: "true"
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: "sleep infinity"
